version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: dbtecnoc_sporys
      MYSQL_USER: dbtecnoc_yusuf
      MYSQL_PASSWORD: 6NY?]He4V#K3

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db
    command: "apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    links:
      - db
